import { ChainKey, Network, Token, TokenType } from "../types"

export enum TokenId {
    SolanaSolMainnet = "solana-sol-mainnet",
    SolanaWsolMainnet = "solana-wsol-mainnet",
    SolanaMsolMainnet = "solana-msol-mainnet",
    SolanaJupMainnet = "solana-jup-mainnet",
    SolanaUsdcMainnet = "solana-usdc-mainnet",
    SolanaSolTestnet = "solana-sol-testnet",
    SolanaWsolTestnet = "solana-wsol-testnet",
    SolanaRayMainnet = "solana-ray-mainnet",
}
export const tokens: Record<ChainKey, Record<Network, Array<Token>>> = {
    [ChainKey.Solana]: {
        [Network.Mainnet]: [
            {
                id: TokenId.SolanaSolMainnet,
                icon: "https://solana.com/img/solana-logo.png",
                name: "Solana",
                symbol: "SOL",
                decimals: 9,
                chainKey: ChainKey.Solana,
                type: TokenType.Native,
            },
            {
                id: TokenId.SolanaWsolMainnet,
                icon: "https://solana.com/img/solana-logo.png",
                name: "Solana",
                tokenAddress: "So11111111111111111111111111111111111111112",
                symbol: "wSOL",
                decimals: 9,
                chainKey: ChainKey.Solana,
                type: TokenType.Wrapper,
            },
            {
                id: TokenId.SolanaMsolMainnet,
                icon: "https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So/icon.png",
                name: "Marinade Staked SOL",
                symbol: "mSOL",
                tokenAddress: "mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So",
                decimals: 9,
                chainKey: ChainKey.Solana,
                type: TokenType.Regular,
            },
            {
                id: TokenId.SolanaJupMainnet,
                icon: "https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/JUP4Fb2cqiRUcaTHdrPC8h2gNsA2ETXiPDD33WcGuJB/icon.png",
                name: "Jupiter",
                symbol: "JUP",
                tokenAddress: "JUP4Fb2cqiRUcaTHdrPC8h2gNsA2ETXiPDD33WcGuJB",
                decimals: 6,
                chainKey: ChainKey.Solana,
                type: TokenType.Regular,
            },
            {
                id: TokenId.SolanaUsdcMainnet,
                icon: "https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v/icon.png",
                name: "USD Coin",
                symbol: "USDC",
                tokenAddress: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
                decimals: 6,
                chainKey: ChainKey.Solana,
                type: TokenType.Stable,
            },
            {
                id: TokenId.SolanaRayMainnet,
                icon: "https://img-v1.raydium.io/icon/4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R.png",
                name: "Raydium",
                symbol: "RAY",
                tokenAddress: "4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R",
                decimals: 6,
                chainKey: ChainKey.Solana,
                type: TokenType.Regular,
            },
        ],
        [Network.Testnet]: [
            {
                id: TokenId.SolanaSolTestnet,
                icon: "https://solana.com/img/solana-logo.png",
                name: "Solana",
                symbol: "SOL",
                decimals: 9,
                chainKey: ChainKey.Solana,
                type: TokenType.Native,
            },
            {
                id: TokenId.SolanaWsolTestnet,
                icon: "https://solana.com/img/solana-logo.png",
                name: "Solana",
                symbol: "wSOL",
                tokenAddress: "So11111111111111111111111111111111111111112",
                decimals: 9,
                chainKey: ChainKey.Solana,
                type: TokenType.Wrapper,
            },
        ],
    },
    [ChainKey.Monad]: {
        [Network.Mainnet]: [],
        [Network.Testnet]: [],
    },
    [ChainKey.Bsc]: {
        [Network.Mainnet]: [],
        [Network.Testnet]: [],
    },
    [ChainKey.Sui]: {
        [Network.Mainnet]: [],
        [Network.Testnet]: [],
    },
}
